// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfwNYa1Q3uSHePYqDvWYqMm3tlu79cVY',
    appId: '1:625170924318:web:43fb755ab1c07bfaa7ff0f',
    messagingSenderId: '625170924318',
    projectId: 'darbonna-9a087',
    authDomain: 'darbonna-9a087.firebaseapp.com',
    storageBucket: 'darbonna-9a087.firebasestorage.app',
    measurementId: 'G-CD4Y5GNFY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzo_Nh20mTJaflAx9FDkxADPYkXXJVXKQ',
    appId: '1:625170924318:android:6e39b1c15a5d7c9da7ff0f',
    messagingSenderId: '625170924318',
    projectId: 'darbonna-9a087',
    storageBucket: 'darbonna-9a087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKc6SCWbyxJ6kJE27ofcojhF63FYkdZbc',
    appId: '1:625170924318:ios:12d6dcaf21f2d75ba7ff0f',
    messagingSenderId: '625170924318',
    projectId: 'darbonna-9a087',
    storageBucket: 'darbonna-9a087.firebasestorage.app',
    iosBundleId: 'com.FadyMonier.DarbonnaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKc6SCWbyxJ6kJE27ofcojhF63FYkdZbc',
    appId: '1:625170924318:ios:301a7701d4b87ceca7ff0f',
    messagingSenderId: '625170924318',
    projectId: 'darbonna-9a087',
    storageBucket: 'darbonna-9a087.firebasestorage.app',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBfwNYa1Q3uSHePYqDvWYqMm3tlu79cVY',
    appId: '1:625170924318:web:352c9d5e40af1ee8a7ff0f',
    messagingSenderId: '625170924318',
    projectId: 'darbonna-9a087',
    authDomain: 'darbonna-9a087.firebaseapp.com',
    storageBucket: 'darbonna-9a087.firebasestorage.app',
    measurementId: 'G-713FXFZB4Q',
  );
}